modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="aim_assistant"
version="1.0.0-1.16.5"
displayName="AimAssistant"
authors="radix-angelicae"
description='''Port of automatic aiming and entity rendering mod for 1.16.5.'''
logoFile="icon.png"

[[dependencies.aim_assistant]]
modId="forge"
mandatory=true
versionRange="[36.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.aim_assistant]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"